[package]
name = "ron"
version = "0.2.0"
license = "MIT/Apache-2.0"
keywords = ["parser", "serde", "serialization"]
authors = [
	"Dzmitry Malyshau <kvarkus@gmail.com>",
	"Thomas Schaller <torkleyy@gmail.com>",
]
description = "Rusty Object Notation"
categories = ["encoding"]
homepage = "https://github.com/ron-rs/ron"
repository = "https://github.com/ron-rs/ron"
documentation = "https://docs.rs/ron/"
exclude = ["bors.toml", ".travis.yml"]

[lib]
name = "ron"

[dependencies]
bitflags = "1"
serde = { version = "1", features = ["serde_derive"] }

[dev-dependencies]
serde_json = "1"
