[package]
name = "ron"
version = "0.1.0"
license = "Apache-2.0"
keywords = ["gamedev"]
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[lib]
name = "ron"

[[example]]
name = "encode"

[dependencies]
rustc-serialize = "*"
