[package]
name = "ron"
version = "0.1.0"
license = "MIT/Apache-2.0"
keywords = ["parser", "serde", "serialization"]
authors = [
	"Dzmitry Malyshau <kvarkus@gmail.com>",
	"Thomas Schaller <torkleyy@gmail.com>",
]
description = "Rusty Object Notation"
categories = ["encoding"]
homepage = "https://github.com/kvark/ron"
repository = "https://github.com/kvark/ron"
documentation = "https://docs.rs/ron/"
exclude = ["bors.toml", ".travis.yml"]

[lib]
name = "ron"

[dependencies]
serde = "1"
pom = "1"

[dev-dependencies]
serde_derive = "1"
